name: Run nodejs index.js
on: [push]
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update
      - name: Install packages
        run: npm install && npm install cloudflared
      - name: Run node.js
        run: node index.js &
